[Variables]
Unit=m
GlobalFontColor=255,255,255
GlobalAccentColor=43,56,255
Color3=0,0,0

;NOTES:

;This below is the settings for the dock with icons.
;If you are not familiar with Rainmeter from earlier,please don't edit anything!
;It's too complicated and sensitive,if you don't know what you doing!
;But i will try to explain to you as much as i can.This "#@#\" is shortened for "@Resources" folder.It's a folder where the icons and other parts of the skin are located.
;If you want to change icon-s,new icon-s,you must put in "@Resources" folder.Also,icons must be in PNG file format.
;When you change "icon and name path",for example if you want to change "My Computer" icon to "CCleaner",it should look like this:

;This is example for some program:

;
;Name1=CCleaner
;TextName1=CCleaner
;LocationPath1=["C:\Program Files\CCleaner\CCleaner64.exe"]

;This is example for some internet links:

;Name2=Twitter
;TextName2=Twitter
;LocationPath2=["https://twitter.com/?lang=en"]

;etc..

;----------------------Icon Dock Settings--------------------------
;------------------------------------------------------------------


;Icon1NameAndPath=#@#\Email.png
;TextName1=Email
;LocationPath1=["https://mail.google.com/mail/"]

;Icon2NameAndPath=#@#\Facebook.png
;TextName2=Facebook
;LocationPath2=["https://facebook.com/"]

;Icon3NameAndPath=#@#\Music.png
;TextName3=Music
;LocationPath3=[Shell:::{1CF1260C-4DD0-4ebb-811F-33C572699FDE}]

;Icon4NameAndPath=#@#\Picture.png
;TextName4=Pictures
;LocationPath4=[Shell:::{3ADD1653-EB32-4cb0-BBD7-DFA0ABB5ACCA}]

;Icon5NameAndPath=#@#\Video.png
;TextName5=Video
;LocationPath5=[Shell:::{A0953C92-50DC-43bf-BE83-3742FED03C9C}]

;Icon6NameAndPath=#@#\Internet.png
;TextName6=Internet
;LocationPath6=["https://www.google.com"]

;Icon7NameAndPath=#@#\Twitter.png
;TextName7=Twitter
;LocationPath7=["https://twitter.com/"]


